### ISSUE TITLE
process.dlopen on Windows

### ISSUE THREAD

**Issue by Raiment57** [buggerjs/bugger#33]
I get this error when trying to use this under Windows 7:

[bugger] Debugging flk.coffee
[bugger] chrome-devtools://devtools/bundled/devtools.html?ws=127.0.0.1:8058/websocket&toolbarColor=rgba(230,230,230,1)&textColor=rgba(0,0,0,1)

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: %1 is not a valid Win32 application.

**Comment by jkrems** [comment]
bugger is no longer using coffee-script, closing this issue.
