### ISSUE TITLE
double attributes

### ISSUE THREAD

**Issue by timsuchanek** [buggerjs/bugger#39]
Hey, first of all: Awesome tool!!!
Really convenient to use, way better then node inspector.

When I console.log variables, all their attributes are shown double.
I'm using node v 0.10.26

![screen shot 2014-03-04 at 00 15 29](https://f.cloud.github.com/assets/1094804/2315897/179c0328-a32a-11e3-9323-ee0803b86dc5.png)

If you need more information, just ask.

Thanks

**Comment by jkrems** [comment]
Should be fixed in 1.0.0
