### ISSUE TITLE
ECONNREFUSED on Ubuntu Server 14 - Accessing as root

### ISSUE THREAD

**Issue by tomhallam** [buggerjs/bugger#41]
Tried running bugger with the default command `bugger myScript.js` and I'm getting the ECONNREFUSED issue. Have tried using the webhost/port command line switches but to no avail.

I'm logged in as root so I wouldn't have thought there were any permissions issues?

Any thoughts?

**Comment by jkrems** [comment]
Since 99% of the way bugger binds to ports has changed, I'll close this ticket.
