### ISSUE TITLE
Can't even install this?

### ISSUE THREAD

**Issue by aleclarson** [buggerjs/bugger#42]
NPM is telling me that `node-gyp rebuild` fails for the `v8-profiler` package.

Are there plans to fix this?

**Comment by jkrems** [comment]
It's a long time since I got around to working on this. And I started the project because `node-inspector` was abandoned back then. I'd definitely accept PRs but when it comes to me digging into it, it's not likely to happen anytime soon.

**Comment by jkrems** [comment]
Should work now.
