### ISSUE TITLE
Make url point to the entry script

### ISSUE THREAD

**Issue by caspervonb** [buggerjs/bugger#53]
Hey @jkrems.

Minor nit issue, `/json/list` returns `file://(...)/node_modules/bugger/lib/io-thread/index.js` as the `url`. Would make more sense if it returned the entry script?

**Comment by jkrems** [comment]
Nice catch! Yeah, that sounds like a bug.

**Comment by caspervonb** [comment]
Hm been digging around a bit but not to sure how to pass data in to the io-thread? `process.title` should probably be reflected in the page title, and the resolved `module.filename` as the url.

**Comment by jkrems** [comment]
My thought was to use the (fake) "argv" like it's currently used for `port`. As long as it's primitive values like strings, that should work. It might start to become a little confusing when it's too many positional arguments, but so far it would be just three (`port`, `process.title`, `mainModule.filename`).

**Comment by caspervonb** [comment]
Sounds good, I was actually expecting it to be in `process.argv[1]` since port was in `argv[2]` but that had the real value ;)

**Comment by jkrems** [comment]
Yeah, the behavior of the io thread ("it pretends to be a separate node process but actually isn't") takes some getting used to. I just blindly copied the pattern from how the [debug API in node itself](https://github.com/nodejs/node/blob/459b106d6cbee05661dee7b3929610d7d06bede0/src/debug-agent.cc#L161) is implemented.

**Comment by caspervonb** [comment]
Fixed in a51a699953b7646219103d6ebbdd77dab698f84e
