### ISSUE TITLE
Unintentional license?

### ISSUE THREAD

**Issue by caspervonb** [buggerjs/bugger#61]
I see that `package.json` is essentially default generated with even author name missing, would you mind explicitly stating the license (license.md or similar)?

It came up a lot with amok when it was becoming semi-popular and by proxy it will be brought up here when i release 2.0 with node support via bugger.

**Comment by jkrems** [comment]
Thanks, that must have happened when switching the master over for 2.0. The LICENSE file is now back and the meta data in package.json as well.

**Comment by jkrems** [comment]
Released v2.2.0 with those changes and also the "one agent per connection" PR.
