### ISSUE TITLE
Profile tab: cpu profile chart view colors unreadable

### ISSUE THREAD

**Issue by aaarichter** [buggerjs/bugger#64]
Hey Jan,

I just tried out the latest version and checked the cpu profiler with the chart view. unfortunately the colors are really bad and the text colors are almost the same as the background colors + they seem to have some text-shadow.

In the chrome dev tools this is not the case. I checked the code but couldn't find where they are defined.

Is it possible to stick to the chrome color scheme?

**Comment by jkrems** [comment]
I just tried it and it worked. Can you describe what steps you tried? What I did:

1. Start an app with `bugger --brk my/entry.js`.
2. Right-click on the tab in the sources panel, select "Reveal in Navigator".
3. It showed the file in the panel on the left.

Is this something related to workspaces?

**Comment by jkrems** [comment]
I'm not doing anything to the colors. How are you opening the devtools? Are you using `chrome-devtools://devtools/bundled/inspector.html?ws=127.0.0.1:8058` or `chrome://inspect/#devices`? Maybe the solution is to just update to a newer revision for the latter.

**Comment by aaarichter** [comment]
Colors are fine - had the same mistake as in issue https://github.com/buggerjs/bugger/issues/65
