### ISSUE TITLE
Q: source tab - file - "reveal in navigator" menu item possible to have?

### ISSUE THREAD

**Issue by aaarichter** [buggerjs/bugger#65]
Hi Jan,

in the chrome dev tools source tab, when a file is open one can right click on the file's tab and select "reveal in navigator" which will focus on the file.

This functionality is really nice to have.
E.g files tend to have common names like "index.js" or "utils.js". When profiling one can click at the file code line, which will open the file the source tab. The problem is that one doesn't know where the file is located.

Is it possible to get this functionality to the source panel?

**Comment by jkrems** [comment]
I just tried it and it worked. Can you describe what steps you tried? What I did:

1. Start an app with `bugger --brk my/entry.js`.
2. Right-click on the tab in the sources panel, select "Reveal in Navigator".
3. It showed the file in the panel on the left.

Is this something related to workspaces?

**Comment by aaarichter** [comment]
ah .. thanks for pointing that out.
I ran `make debug` - that wasn't using bugger but note-debug.

awesome works
