### ISSUE TITLE
Cannot run any console commands when in breakpoint

### ISSUE THREAD

**Issue by stenver** [buggerjs/bugger#68]
No matter what console command I run, I get this error message:
```
Uncaught ReferenceError
message: "__buggerCLI is not defined"
stack: (...)
get stack: ()
set stack: ()
```

I am running jest tests with the following command:

```
node --harmony $(which bugger) ./node_modules/jest-cli/bin/jest.js --runInBand
```
Also tried to use this command:
```
bugger ./node_modules/jest-cli/bin/jest.js  #--runInBand
```

**Comment by jkrems** [comment]
Thanks! I definitely can reproduce and it seems to happen only with jest. Investigating.

**Comment by jkrems** [comment]
The problem might be that jest runs the tests in a context where `global` refers to a fake / JSDOM window, not node's `global` object. And bugger depends on a global value to provide the console API. Will try to make it degrade gracefully.

**Comment by jkrems** [comment]
Can you give v2.2.3 a try?

**Comment by stenver** [comment]
Works great! Thanks!
