### ISSUE TITLE
How can I use this with Babel?

### ISSUE THREAD

**Issue by JesseAldridge** [buggerjs/bugger#73]
Hey there.  I'm a non javascript developer that recently inherited a js project.  Bugger was recommended by the previous developer.  I can run my project's es6 test suite by doing `bugger ./node_modules/.bin/_mocha`.  And it seems like the transpilation happens on the fly just fine.  But I can't figure out how to run an individual file.  I can do `babel-node test/load_test.js`, but `bugger test/load_test.js` obviously doesn't work.  Is there a way to do something like `bugger --babel-node test/load_test.js`?  I don't see anything along these lines in the readme.

Sorry if opening a ticket is inappropriate for this question :)

**Comment by JesseAldridge** [comment]
Gah.  Figured it out literally 10 seconds after posting this...

`babel-node $(which bugger) test/load_test.j `

**Comment by duncanbeevers** [comment]
@JesseAldridge Thanks for posting your findings. Hopefully the next dev will find an answer in 5 seconds instead of 10.
